spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://localhost:8071"

logging:
  level:
    com.within.gatewayserver: DEBUG
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
